language: java

jdk:
  - oraclejdk11
  
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

script:
  - (cd japproval-core && gradle clean build publishToMavenLocal)
  - (cd japproval-gradle-plugin && gradle clean build publishToMavenLocal)
  - (cd japproval-example && gradle clean build)

