language: java

jdk:
  - oraclejdk11
  
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

script:
  - (cd japprove-core && gradle clean build publishToMavenLocal)
  - (cd japprove-gradle-plugin && gradle clean build)
  - (cd japprove-maven-plugin && mvn clean install)
